### ISSUE TITLE
Retain comments in autoformatter

### ISSUE THREAD

**Issue by breckbaldwin** [rok-cesnovar/stanc3js-demo#1]
parameters { // keep this comment
real y;
}
model {
y
 ~ std_normal();
}

loses the comment, makes it difficult to use as a linter.
```
parameters {
  real y;
}
model {
  y ~ std_normal();
}
```
If agreed I'll look into implementing it.

Breck

**Comment by rok-cesnovar** [comment]
Hey, yeah it's the same for the canonicalizer, unfortunately. The problem here is that stanc3 does not retain comments in the AST and hence the auto-formatter as well. This is waiting on https://github.com/stan-dev/stanc3/pull/603, once that is in, it will automatically work.

**Comment by breckbaldwin** [comment]
I read the thread at stan-dev/stanc3#603, so should wait for that to be resolved. I saw your bump. 

How far are you interested in going with this UI? I have a crappy linter that just complains about issues at:

https://github.com/breckbaldwin/stan_linter

Linters don't typically modify code, just complain. This helps teach good coding habits as well as clean up code. But it is distinct from an auto formatter. Are you interested in adding a 'linter' tab? I guess I'd have to translate the python linter into javascript if so?

**Comment by rok-cesnovar** [comment]
> How far are you interested in going with this UI?

Haven't really thought much about where to go with all this. The first thing is making it look decent, and as far as I am concerned we can add anything that can run in Javascript and does not require server-side resources.

Do you have a written set of rules your linter follows?

**Comment by breckbaldwin** [comment]
Yes, the linter is a series of rules that go through line by line. 
I think your interface looks fine but I am very old school on UIs. 
I'll see if there is a straight forward way to add the linter--it can always be yanked later.

**Comment by spinkney** [comment]
leaving comments works now

**Comment by rok-cesnovar** [comment]
Thanks Sean, that is correct. Closing.
