### ISSUE TITLE
Add max-line-length to auto-format

### ISSUE THREAD

**Issue by rok-cesnovar** [rok-cesnovar/stanc3js-demo#10]

**Comment by WardBrian** [comment]
You may want to consider adding this to the canonicalizer page as well? (or perhaps simply merge them, with the check boxes all defaulting to off?)

**Comment by rok-cesnovar** [comment]
Will add it to the canonicalizer and think about merging them in the future.

**Comment by rok-cesnovar** [comment]
Done, thanks!
