### ISSUE TITLE
[FR] Add line numbers

### ISSUE THREAD

**Issue by spinkney** [rok-cesnovar/stanc3js-demo#9]
Can we add line numbers to the input box and the output?

Btw, I'm using this as I write a lot of my stan programs now, it's so nice and easy. We need to get a plugin or something available on vs code

**Comment by rok-cesnovar** [comment]
Yeah, the line numbers will be added together with fixing https://github.com/rok-cesnovar/stanc3js-demo/issues/5

It will use the live prism.js, see here https://live.prismjs.com/

**Comment by spinkney** [comment]
Does that include the input box? It seems like it but the demo shows for output. Just double checking. This is useful for when the code errors and you need to go fix the problematic line. Right now I'm going back and forth between an editor and the box.

**Comment by rok-cesnovar** [comment]
Yeah, this is for the input text area. All examples in the links are text areas, you can write in them.

**Comment by rok-cesnovar** [comment]
Added line numbers today.
